#!/bin/bash
INPUT=$1  # both single-end and paired-end data are fed as a single fastq file.
INDEX=$2
OUTDIR=$3
PREFIX=$4
NTHREADS=$3
  
ISPAIRED=$(head -n 8 $INPUT | paste - - - - | awk '{print $1}' | uniq -c | awk '{print $1}' | head -n 1)
if [[ $ISPAIRED -eq 2 ]]; then
  PAIRARG="-p"
  >&2 echo "fastq is interleaved, treating as paired-end"
else
  PAIRARG=""
  >&2 echo "fastq is not interleaved, treating as single-end"
fi

# check if file exists
if [[ ! -f $INPUT ]]; then echo "fastq file \"$INPUT\" not found"; exit 1; fi

OUTPUT=$OUTDIR/$PREFIX.bam
LOGFILE=${OUTPUT}.log

bwa mem $PAIRARG -v 2 -t $NTHREADS $INDEX $INPUT | samtools view -Shb - > $OUTPUT
echo $OUTPUT

