#!/usr/bin/env bash
INPUT=$1
CHROMSIZE=$2
OUTDIR=$3
OUTPREFIX=$4
WINSIZE=$5

if [ -z $OUTDIR ]; then
  OUTDIR=.
fi

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

if [ -z $WINSIZE ]; then
  WINSIZE=5000
fi

# check if file exists
if [[ ! -f $INPUT ]]; then >&2 echo "file \"$INPUT\" not found"; exit 1; fi
if [[ ! -f $CHROMSIZE ]]; then >&2 echo "file \"$CHROMSIZE\" not found"; exit 1; fi

# output file name
BASE=$OUTDIR/$OUTPREFIX
OUTPUT=${BASE}.w${WINSIZE}.bg
BINFILE=${BASE}.w${WINSIZE}.bin
COVERAGEFILE=${BASE}.w${WINSIZE}.cov

# determine scale
SCALE=$(echo "1000000/$(samtools view -c $INPUT)" | bc -l)
  
# run count command
bedtools makewindows -w $WINSIZE -g $CHROMSIZE > $BINFILE
{ # try
    # This command returns 1 even when it succeeds. This try/catch is to prevent this script from exiting with 1 when run successfully.
    bedtools coverage -counts -sorted -c -a $BINFILE -b $INPUT > $COVERAGEFILE
} || { # catch
    true
}

awk -v scale=$SCALE '{print $1,$2,$3,$4*1000*(scale/($3-$2)) }' OFS='\t' $COVERAGEFILE > $OUTPUT
