#!/usr/bin/env bash
INPUT=$1
OUTDIR=$2
OUTPREFIX=$3
  
# check if file exists
if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi

# default options
if [ -z $OUTDIR ]; then
  OUTDIR=.
fi

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

# PE vs SE
UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
  
if [[ UCOUNT -lt 1000 ]]; then
  PAIRARG=""  # PE
else
  PAIRARG="-s"  # SE
fi 

# output and log file names
BASE=$OUTDIR/$OUTPREFIX
OUTPUT=${BASE}.rmdup.bam
LOGFILE=${BASE}.rmdup.bam.log

# run dedup command
samtools rmdup $PAIRARG $INPUT $OUTPUT 2> $LOGFILE
