#!/usr/bin/env bash
# usage : outdir outprefix minrpkm inputbg1 inputbg2 inputbg3 ...
OUTDIR=$1
OUTPREFIX=$2
MINRPKM=$3  # e.g. 0.1
shift
shift
shift

INFILESTR=${@}
INFILES=(${INFILESTR// / })
NFILES=${#INFILES[@]}

FILTERED_BED=$OUTDIR/$OUTPREFIX.filtered.bed

paste $INFILESTR | awk -v minrpkm=$MINRPKM \
  '{for(i=4;i<=NF;i+=4){scoresum+=$i}; if((scoresum/(NF/4))>=minrpkm){print $1,$2,$3};scoresum=0}' \
OFS='\t' > $FILTERED_BED
